services:
  - type: web
    name: smartfinance-demo
    env: docker
    region: singapore
    plan: free
    envVars:
      - key: APP_NAME
        value: SmartFinance
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:TpjXzWU21rPdhzcXs+sUVEVvzlgGt45zosjnpfbz9ug=
